/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 6.0.0   2016-10-17

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/


/* Includes */
#include <stddef.h>
#include "stm32l1xx.h"
#include <vrs_cv5.h>


volatile int valueOfRegister, odosli=0, posun=0, pocznakov=0;
volatile int isFlag = 0;
volatile char buffer[50];


void ADC1_IRQHandler(void)
{
	if (ADC1->SR & ADC_SR_EOC)
 	{
 		valueOfRegister = ADC1->DR;
 	}
}

void USART2_IRQHandler(void)
{
	uint8_t pom = 0;
	int pom2=0;
	if(USART_GetITStatus(USART2, USART_IT_TC) != RESET)
	{

		USART_ClearITPendingBit(USART2, USART_IT_TC);  // vynulovanie flagu prerusenia ktory uz bol

		if(posun<pocznakov && pocznakov<50)
		{
			/*if(buffer[posun]=='\0')
			{
				posun++;
			}*/
			//else
			//{
				USART_SendData(USART2, buffer[posun]);
				while (USART_GetFlagStatus(USART2, USART_FLAG_TC) == RESET);
				posun++;
				/*if (isFlag == 1)
				{
					if(pom2 == 0)
					{
					pom2 =1;
					USART_SendData(USART2, 'V');
					while (USART_GetFlagStatus(USART2, USART_FLAG_TC) == RESET);

					}
					else
					{
						pom2 =0;
					}

				}*/
			//}


		}
		else
		{
			posun = 0;
			pocznakov=0;
		}
	}
	if(USART_GetITStatus(USART2, USART_IT_RXNE) != RESET)
	{
		USART_ClearITPendingBit(USART2, USART_IT_RXNE);
		pom = USART_ReceiveData(USART2);
		// ak prijimeme m-ko
		if(pom == 'm')
		{
			if(isFlag == 0){
				isFlag = 1;
			}
			else{
				isFlag = 0;
			}
		}
	}
}


/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{

  int AD_value, i;
  char c[5];
  GPIO_InitTypeDef
  GPIO_InitStructure;

  RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOA,ENABLE);
  GPIO_InitStructure.GPIO_Mode=GPIO_Mode_OUT;
  GPIO_InitStructure.GPIO_OType=GPIO_OType_PP;
  GPIO_InitStructure.GPIO_PuPd=GPIO_PuPd_UP;
  GPIO_InitStructure.GPIO_Speed=GPIO_Speed_40MHz;
  GPIO_InitStructure.GPIO_Pin =GPIO_Pin_5;
  GPIO_Init(GPIOA, &GPIO_InitStructure);

  Init();
  Intpre();
  initUSART2();

  /* Nastavenie AD prevodnika na neustalu kom */
  ADC_SoftwareStartConv(ADC1);
  while(!ADC_GetFlagStatus(ADC1, ADC_FLAG_EOC)){}
  USART_ITConfig(USART2, USART_IT_RXNE, ENABLE);
  USART_ITConfig(USART2, USART_IT_TC, ENABLE);
  // Enable USART
  USART_Cmd(USART2, ENABLE);

  //povolenie prerusenia
  ADC_ITConfig(ADC1, ADC_IT_EOC, ENABLE);

  while(1)
  {
  	 GPIO_SetBits(GPIOA, GPIO_Pin_5);
     for(i=0; i<valueOfRegister*100; i++) {}
  	 GPIO_ResetBits(GPIOA, GPIO_Pin_5);
  	 for(i=0; i<valueOfRegister*100; i++) {}


  	 // posleme na USART2


  	 if(isFlag == 1)
  	 {
  			AD_value=(33*valueOfRegister)/4096;
  	 }
  	 else
  	 {
  			AD_value=valueOfRegister;
  	 }
     sprintf(c, "%d\t", AD_value);
     for(int cas=0;cas<=30000;cas++);
  		if(pocznakov==0)
  		{
  			USART_SendData(USART2, c[0]);

  			for(i=1;i<6;i++)
  			{
  				buffer[pocznakov]=c[i];
  				pocznakov++;
  		    }
  		 }
  		else
  		{
  		    for(i=0;i<6;i++)
  		    {
  		       buffer[pocznakov]=c[i];
  		       pocznakov++;
  		    }
  		    }

  }

  /**
  *  IMPORTANT NOTE!
  *  See the <system_*.c> file and how/if the SystemInit() function updates 
  *  SCB->VTOR register. Sometimes the symbol VECT_TAB_SRAM needs to be defined 
  *  when building the project if code has been located to RAM and interrupts 
  *  are used. Otherwise the interrupt table located in flash will be used.
  *  E.g.  SCB->VTOR = 0x20000000;  
  */

  /**
  *  At this stage the microcontroller clock setting is already configured,
  *  this is done through SystemInit() function which is called from startup
  *  file (startup_stm32l1xx_hd.s) before to branch to application main.
  *  To reconfigure the default setting of SystemInit() function, refer to
  *  system_stm32l1xx.c file
  */

  /* TODO - Add your application code here */


  return 0;
}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}
